require('config.telescope')
require('config.treesitter')
require('config.compe')
require('config.colorscheme')
require('config.lsputils')
require('config.lspconfig')
-- require('config.devicon')
-- require('config.rainbow')
-- require('config.colorizer')
-- require('config.fugitive')
-- require('config.completion')
-- require('config.neogit')
-- require('config.lspkind')
-- require('config.project')